# 서버 포트 설정
server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripbuddy
    username: root
    password: june108301@
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 0
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
    session:
      timeout: 30m
  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: yoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkey
  expiration: 3600000